---
title: "fire-color: pull data"
subtitle: "identifying post-fire color changes in lakes of the western U.S."
author: "Bella Oleksy et al. "
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::pdf_document2:
    latex_engine: pdflatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir='..')
knitr::opts_chunk$set(out.width = '100%',fig.height=5,
                      echo=FALSE, 
               warning=FALSE, message=FALSE) 

```

```{r some package version control stuff, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
##Hi! If you have never used renv read their little vignette here. 
##https://rstudio.github.io/renv/articles/renv.html

##If you've ever had script not work after updating R/various libraries, using
##renv() is a nice way to avoid a lot of future headaches. -IAO

if (!require('renv')) install.packages('renv');library('renv')

#Create a lockfile for packages
# renv::init()
```


```{r Load necessary packages, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
if (!require('here')) install.packages('here');library('here')
##enable easy file referencing in project-oriented workflows.
##https://rstats.wtf/project-oriented-workflow.html
## ^ ^ a little more on that

source(here("scripts/00_libraries.R"))
```
